#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "pp: This script must be run as root (or with sudo)."
  echo "(This script is safe and does NOT contain ANY malicious code.)"
  echo "(You can verify this by going to https://github.com/8a0k37/not-sus)"
  exit 1
fi


#WARNING: ALL CODE IN THE DIRECTORY not-sus IS OWNED BY 8a0k37.
#COPYING THE CODE OR USING IT FOR COMERCIAL PURPOSES IS STRICTLY PROHIBITED!
echo "Setting up pp..."
sleep 1.3
echo "Enter your username to setup"
echo "the permissions correctly."
read -p "Username: " username
mv .pp pp
mv pp /bin
mkdir /.pp_essential
mv .pp_config.conf pp_config.conf
mv pp_config.conf /.pp_essential
chmod u+x /bin/pp
chmod u+wr /.pp_essential/pp-config.conf
chmod -wrx /.pp_essential
chmod u+wrx /.pp_essential
chown ${username}:${username} /.pp_essential
chown ${username}:${username} /.pp_essential/pp_config.conf
echo "Using '${username}'..."
sleep 2
echo "Done."
sleep 0.7
echo "type 'pp' to use the command."
sleep 1.4
echo "To check for updates type 'sudo pp --update'."
sleep 1.5
echo "To re-setup type 'sudo pp --resetup'."
echo "FOR MORE INTO TYPE 'pp --help'."
sleep 2.3
echo "You can find all the essential files and"
echo "the main config in '/.pp_essential'."
sleep 0.8
echo "(Use 'sudo cd /.pp_essential')"
sleep 2
echo "Thank you for using pp."
sleep 2
echo "- Your pp"
./.finish
rm -- "$0"
